backend: sdk
camera_backend: realsense
arms:
  left_can: can0
  right_can: can2
enable_on_connect: false
speed_ratio: 100
high_follow: true
gripper_open_raw: 70000
gripper_closed_raw: 0
cameras:
  front:
    backend: realsense
    device: 347622070427
    width: 640
    height: 480
    fps: 30
  left_wrist:
    backend: realsense
    device: 260322278131
    width: 640
    height: 480
    fps: 30
  right_wrist:
    backend: realsense
    device: 335122272832
    width: 640
    height: 480
    fps: 30

